### ISSUE TITLE
Import project on VScode

### ISSUE THREAD

**Issue by gregonthegit** [jjsch-dev/pico_i2c_sniffer#3]
Hello jjsch-dev,

I test your code on a I2C at 400kHz and it work perfectly.

I use the .uf2 to download the code, but it is compiled and I can not adapte it to my need.
Could you give me the code?

Did you develop on Thonny or VsCode?

Thanks

**Comment by DarkElvenAngel** [comment]
I too want to make changes, but the code is in the repo here, you can build it from source.

The code is in C and there is a .vscode folde

**Comment by gregonthegit** [comment]
I see my error and open a new project on VScode add paste all necessary files.
Now I have some errors linked to the declaration of some variable on "i2c_sniffer.pio"
<img width="960" alt="VScode_error" src="https://github.com/jjsch-dev/pico_i2c_sniffer/assets/93545806/784cc98c-4838-4b28-a1b7-fd17085fed22">

I am new with VScode

**Comment by gregonthegit** [comment]
I close the issue because it is a VScode configuration problem.

I found help on:
https://www.raspberrypi.com/news/raspberry-pi-pico-windows-installer/
and
https://www.youtube.com/watch?v=mUF9xjDtFfY

**Comment by jjsch-dev** [comment]
Hello @gregonthegit , it's good that it worked for you with 400Khz, I compiled the code a long time ago with VScode, it may not work now, if you have problems and I can help you, let me know.

**Comment by gregonthegit** [comment]
Hello jjsch-dev, 
Yes it is a vscode installation and vscode use which is my problem, I install all on a raspberry PI 4 and I am able to compile it.
